# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-08 21:19
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Researchgroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchgroupUserBinding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('researchgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.Researchgroup')),
            ],
        ),
        migrations.CreateModel(
            name='ScopeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gitlab_id', models.IntegerField(null=True)),
                ('uid', models.IntegerField(null=True)),
                ('gid', models.IntegerField(null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('token', models.CharField(max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='researchgroupuserbinding',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.User'),
        ),
    ]
