# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-09 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchgroupuserbinding',
            name='researchgroup',
        ),
        migrations.RemoveField(
            model_name='researchgroupuserbinding',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gitlab_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.DeleteModel(
            name='Researchgroup',
        ),
        migrations.DeleteModel(
            name='ResearchgroupUserBinding',
        ),
    ]
